### ISSUE TITLE
ERROR & CORRECTIONS

### ISSUE THREAD

**Issue by rajeshjeshar** [sagarchoudhary96/Flutter-Chat#1]
in the following line it shows error:
`itemBuilder: (_, DataSnapshot snapshot, Animation<double> animation) {`

**Error message:**
"message": "The argument type '(BuildContext, DataSnapshot, Animation<double>) → ChatMessage' can't be assigned to the parameter type '(BuildContext, DataSnapshot, Animation<double>, int) → Widget'."

**CORRECTIONS:**
line 204:
 `child: new GoogleUserCircleAvatar(snapshot.value['senderPhotoUrl']),`   has to be changed as 

                `child: new GoogleUserCircleAvatar(identity: snapshot.value['senderPhotoUrl'],),`

**Comment by sagarchoudhary96** [comment]
thanks :) will check it out and fix it
